### ISSUE TITLE
random freezes

### ISSUE THREAD

**Issue by Stricted** [Exynos7580/android_kernel_samsung_exynos7580-common#4]
somehow the kernel seems to cause random freezes and app crashes from time to time

i have no idea why and how, the logs are clean (no indication of a freeze)

**Comment by alexax66** [comment]
I will fix it

**Comment by alexax66** [comment]
Do you use kernel with this commit https://github.com/Exynos7580/android_kernel_samsung_exynos7580-common/commit/09665e41974fc8ff691536425b8b77e91f582b5d ?
Try disable CPUSETS again  if used

**Comment by Stricted** [comment]
cpusets is disabled

**Comment by alexax66** [comment]
OK!

**Comment by alexax66** [comment]
Try using some changes from this commit https://github.com/Exynos7580/android_kernel_samsung_exynos7580-common/commit/90f1fdd578f1c9466f11a3cad2604fc706c6ab40
See also this diff.txt https://drive.google.com/file/d/0B6vI9V6s4jvbQ0U2NVhUZU11VDQ/view?usp=sharing
I haven't any problem with exynos7580-common kernel

**Comment by Stricted** [comment]
will apply that later, we will see in the next build then if it fixes anything

for myself i dont have the problem but a few users reportet that the phone randomly freezes and apps randomly crashes

**Comment by Stricted** [comment]
i applied the changes in 487687da2b8501447cb71154684b57620a7447ca
its a bit less laggy but it still freezes
in comparsion i did a test build with the a3 kernel, on the a3 kernel there are no lags and no freezes

**Comment by alexax66** [comment]
Try revert this commit https://github.com/Exynos7580/android_device_samsung_s5neoltexx/commit/44745254a4b635b24b84ed1a4815738b58bb4083
Apply this commit  https://github.com/Exynos7580/android_kernel_samsung_exynos7580-common/commit/09665e41974fc8ff691536425b8b77e91f582b5d
and this https://github.com/Exynos7580/android_device_samsung_a3xeltexx/commit/6efebb9a08c2b075fc691dd9376fb01dbe649e82

**Comment by Stricted** [comment]
did an test build with that and its lagging like hell and the freezes are still there
i probably go back to the a3 kernel

**Comment by alexax66** [comment]
OK!
It's strangely. No lags for me.
I will try fix this problem

**Comment by Stricted** [comment]
thank you,

yep its strange also the logs give no hints why that is happening

**Comment by alexax66** [comment]
I reverted some  suspicious commits and return Cafactive as default 
https://github.com/Exynos7580/android_kernel_samsung_exynos7580-common/commits/los-14.1
Also need made this 
https://github.com/Exynos7580/android_device_samsung_a3xeltexx/commit/9ee933ec3e8c74e0ae3588f88770ba5d65220fca
I highly recommend using this commit for 8 cores
https://github.com/Exynos7580/android_device_samsung_a3xeltexx/commit/6efebb9a08c2b075fc691dd9376fb01dbe649e82

**Comment by Stricted** [comment]
sounds good, will do a test build and report how its going

**Comment by alexax66** [comment]
Need test on s5neo
All good on a3xelte

**Comment by Stricted** [comment]
alright got the response from my tester
lagging is still there (i guess caused by cpusets)
and the phone freezes now after a couple of hours
its pretty weird that we have only on the s5 neo these problems

**Comment by alexax66** [comment]
I think need use specific power hal for device s5neo too: https://github.com/Exynos7580/android_device_samsung_a3xeltexx/commits/cm-14.1/power

**Comment by Stricted** [comment]
with the power hal in the device tree https://github.com/Exynos7580/android_device_samsung_s5neoltexx/commit/4da01939fa8e988a03625eac32dcd47da45967a1 the lags are nearly gone
but the phone still freezes after 5h
something is still wrong

**Comment by alexax66** [comment]
I did some research and found that the LMK is not working properly. This is my mistake
I made some fixes for it in the kernel https://github.com/Exynos7580/android_kernel_samsung_exynos7580-common/commits/los-14.1
I hope this helps
Another benefit is to use the sswap:
https://github.com/Exynos7580/android_device_samsung_a3xeltexx/commit/537994a197c3700d58bc68ec0f42b10b878748c7
https://github.com/Exynos7580/android_device_samsung_a3xeltexx/commit/02cd5ec5bd19d22ec0f4a9f949e3a33b7d89c49d
https://github.com/Exynos7580/android_device_samsung_a3xeltexx/commit/4ea0fa12d857528cb42e8456988ea0af732cecbf
https://github.com/Exynos7580/android_device_samsung_a3xeltexx/commit/bd931fd81a2fa60c72be53faceecfa8e4699ab98

**Comment by alexax66** [comment]
I found cause of freezing 
There are no freezes after apply this [commit](https://github.com/Exynos7580/android_kernel_samsung_exynos7580-common/commit/5dc81da4b450de54cf59018e6a5839e2c87fe421) even if is used the sswap

**Comment by Stricted** [comment]
can confrm that
after the automated test build if got good responses that the freezes and lags are gone
i close here for now
