### ISSUE TITLE
a5xtltexx doesnt boot

### ISSUE THREAD

**Issue by itsmerajit** [Exynos7580/android_kernel_samsung_exynos7580-common#5]
successfully build lineage os. but doesnt boot . i have use this kernel. while i have used another boot.img from Ressurection rom  from another dev and its booted. not able to tale last_kmsg aswell.

**Comment by alexax66** [comment]
I think need revert this coomit https://github.com/Exynos7580/android_kernel_samsung_exynos7580-common/commit/487687da2b8501447cb71154684b57620a7447ca

**Comment by alexax66** [comment]
This not suitable for A5

**Comment by itsmerajit** [comment]
which would do the job? this one?  https://github.com/Exynos7580/android_kernel_samsung_a5xelte.git

:(

**Comment by ghost** [comment]
I can't understand that, because this is the kernel used in RR.

**Comment by itsmerajit** [comment]
bro are you angry on me? if you need i can send you the build image. and sorry for the boot.img. i didn't take permission

**Comment by ghost** [comment]
Yes and it's useless to send me build image, i don't have a5.
Anyway it's weird because i pushed all commits on the organization and i have a working compilation and boot on RR A5. So check what you did.

**Comment by itsmerajit** [comment]
make clean already done. now working with  https://github.com/Exynos7580/android_kernel_samsung_a5xelte.git .

**Comment by itsmerajit** [comment]
succesfully build with a5xeltexx kernel. 
random bootloop now cat take last_kmsg
do you need anything now ??

**Comment by ghost** [comment]
why are you using the a5xelte kernel ._. ?
The common kernel is updated and stable.

**Comment by itsmerajit** [comment]
just giving a shot .. anyway here the logcat https://pastebin.com/nRGjs06e

**Comment by itsmerajit** [comment]
dont understand why my build doest boot with inbuild boot.img and its boot with your boot.img .. :/ did you forgot to push anything ?

**Comment by ghost** [comment]
I pushed all.
Anyway, for you logcat, all seems good except fatal error for nfc (no fix actually) and gpsd (i didn't worked on actually)

**Comment by itsmerajit** [comment]
the kernel size is actually bigger in my case [boot.img] mine 18.3mb
RR boot.img 16mb .. some thing fishy :100:

**Comment by ghost** [comment]
common kernel is optimized and has some removed things (knox, tima, and other crap from samsung)

**Comment by itsmerajit** [comment]
that also failed to boot in my case..haha

**Comment by ghost** [comment]
Closed for inactivity (and anyway i think it's solved).
