### ISSUE TITLE
Stock kernel

### ISSUE THREAD

**Issue by Sekilsgs2** [Exynos7580/android_kernel_samsung_exynos7580-common#7]
Hi all..
I'm try make RR better and - 
1. stock kernel from alexax66 work on RR very good (with RR ramdisk)!  https://github.com/alexax66/kernel_a3xelte_nougat
2. gralloc.exynos5.so - need from stock nogat (old dont work with mali r15p0)!
3. libGLES_mali.so - need from stock nogat (for mali r15p0)
4. disable sswap  -  freeze system after some times (but i'm cant test on stock kernel from alexax66 only test with  this kernel). System freeze with kswapd and mmcqd services from kernel...

And we really need this in build.prop?
```
# Exynos
debug.hwc.force_gpu=1
```
i'm add this to build.prop - 
```
ro.opengles.version=196609
debug.hwc.otf=1
debug.hwc.winupdate=1
```

And after this changes RR working very very good (but battery cant test - need time)

i'm think linage with this working well too....

**Comment by ghost** [comment]
Wow thanks!
I already updated libGLES_mali.so to Nougat
For kernel, i agree (when i use a kernel based on A3 (like this: https://github.com/Exynos7580/android_kernel_samsung_a3xelte), i have less lags)
For gralloc and sswap, i don't know, never tested
Thanks :+1:

**Comment by alexax66** [comment]
Common-kernel has r15p0 revision MALI driver:
https://github.com/Exynos7580/android_kernel_samsung_exynos7580-common/commit/34a814911fa261426faf9a209ad69dbe46f49f98
https://github.com/Exynos7580/android_kernel_samsung_exynos7580-common/commit/b32b559eb42a25008a1bafdfaa23984b630c3c04
